# This is a basic workflow to help you get started with Actions

name: Add row to data.csv

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  writeData:
    runs-on: ubuntu-latest
    steps:
      - name: checkout main branch
        uses: actions/checkout@v2
      - uses: gr2m/write-csv-file-action@v1.x
        with:
          path: _data/stats.csv
          columns: Column 1, Column 2, etc
          "Column 1": 1
          "Column 2": 2
          etc: 3
