name: Run CI
on: [push]
jobs:
  Run-All-Tests:
    name: "incorporate data"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: process data
        run: python test_flow.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bot] Update all the things!"
          commit_user_name: zach_web_bot
          commit_user_email: zschutzman@gmail.com
          commit_author: zach_web_bot
