name: Run CI
on: [push]
jobs:
  Run-All-Tests:
    name: "incorporate data"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: process data
        run: pip install pandas && python .github/workflows/test_flow.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bot] Update all the things!"
          commit_user_name: zach-web-bot
          commit_user_email: zschutzman@gmail.com
          commit_author: zach-web-bot <zschutzman@gmail.com>
