name: Incorporating new data
on:
  workflow_dispatch:
  schedule:
    - cron: "*/60 * * * *"
jobs:
  Run-All-Tests:
    name: "incorporate data"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: process data
        run: pip install pandas && python .github/workflows/update_data.py
      - name: cleanup
        run: rm -rf _data/hot-or-not/raw/dat_*
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "incorporating new data"
          commit_user_name: zach-web-bot
          commit_user_email: zschutzman@gmail.com
          commit_author: zach-web-bot <zschutzman@gmail.com>
